<#
.SYNOPSIS
    Downloads yi-hack-allwinner-v2 firmware for the YI Outdoor 1080p (YHS.3017),
    injects the local-gateway config, and writes everything to a microSD card.

.USAGE
    # Preview only (no card write):
    .\prep-flash-sd.ps1 -DryRun

    # Write to SD card at drive E:
    .\prep-flash-sd.ps1 -SdDrive E
#>
param(
    [string]$SdDrive = "",       # Drive letter of the SD card (e.g. "E")
    [string]$GatewayIp = "",     # Auto-detected if blank
    [switch]$DryRun              # Just download + stage; don't write to SD
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Config ──────────────────────────────────────────────────────────────────
$CameraModel    = "yi_outdoor_1080p"
$RepoApi        = "https://api.github.com/repos/alienatedsec/yi-hack-allwinner-v2/releases/latest"
$StageDir       = Join-Path $PSScriptRoot "..\flash-staging"
$ConfigTemplate = Join-Path $PSScriptRoot "..\flash-config\yi.cfg"

# Auto-detect gateway IP (first 10.0.0.x Ethernet address)
if (-not $GatewayIp) {
    $GatewayIp = (Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object { $_.IPAddress -match "^10\." } |
        Select-Object -First 1).IPAddress
    if (-not $GatewayIp) { $GatewayIp = "10.0.0.112" }
}

Write-Host ""
Write-Host "=== YI Camera Flash Prep ===" -ForegroundColor Cyan
Write-Host "  Camera model : $CameraModel"
Write-Host "  Gateway IP   : $GatewayIp"
Write-Host "  Stage dir    : $StageDir"
Write-Host "  SD drive     : $(if($SdDrive){"${SdDrive}:"}else{'(none - dry run)'})"
Write-Host ""

# ── Step 1: Fetch latest release info ───────────────────────────────────────
Write-Host "[1/5] Fetching latest yi-hack-allwinner-v2 release..." -ForegroundColor Yellow
$release = Invoke-RestMethod -Uri $RepoApi -Headers @{ "User-Agent" = "camcontrol-flasher" }
$tag     = $release.tag_name
Write-Host "      Latest tag: $tag"

# Find the asset for the outdoor 1080p model
$asset = $release.assets | Where-Object { $_.name -like "*$CameraModel*" } | Select-Object -First 1
if (-not $asset) {
    # Fall back to the first zip (some releases pack all models together)
    $asset = $release.assets | Where-Object { $_.name -like "*.zip" } | Select-Object -First 1
}
if (-not $asset) {
    Write-Error "No firmware asset found in release $tag. Check https://github.com/alienatedsec/yi-hack-allwinner-v2/releases"
}
Write-Host "      Asset     : $($asset.name)  ($([math]::Round($asset.size/1MB,1)) MB)"

# ── Step 2: Download ─────────────────────────────────────────────────────────
$DownloadDir = Join-Path $env:TEMP "yi-hack-download"
New-Item -ItemType Directory -Path $DownloadDir -Force | Out-Null
$ZipPath = Join-Path $DownloadDir $asset.name

if (Test-Path $ZipPath) {
    Write-Host "[2/5] Already downloaded. Skipping." -ForegroundColor Green
} else {
    Write-Host "[2/5] Downloading $($asset.name)..." -ForegroundColor Yellow
    Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $ZipPath -UseBasicParsing
    Write-Host "      Download complete."
}

# ── Step 3: Extract to staging area ──────────────────────────────────────────
Write-Host "[3/5] Extracting to staging area..." -ForegroundColor Yellow
if (Test-Path $StageDir) { Remove-Item $StageDir -Recurse -Force }
New-Item -ItemType Directory -Path $StageDir -Force | Out-Null
Expand-Archive -Path $ZipPath -DestinationPath $StageDir -Force

# If the zip has a single sub-folder, move contents up
$subDirs = Get-ChildItem $StageDir -Directory
if ($subDirs.Count -eq 1) {
    $inner = $subDirs[0].FullName
    Get-ChildItem $inner | Move-Item -Destination $StageDir
    Remove-Item $inner
}

# Find the model-specific subdirectory
$modelDir = Get-ChildItem $StageDir -Directory | Where-Object { $_.Name -like "*outdoor*" -or $_.Name -like "*$CameraModel*" } | Select-Object -First 1
if ($modelDir) {
    Write-Host "      Model dir : $($modelDir.Name)"
    $flashRoot = $modelDir.FullName
} else {
    $flashRoot = $StageDir
}

# ── Step 4: Inject gateway config ─────────────────────────────────────────────
Write-Host "[4/5] Writing yi.cfg with local gateway config..." -ForegroundColor Yellow

$yiCfg = @"
# yi-hack configuration — auto-generated by camcontrol flash prep
# Gateway: http://${GatewayIp}:8080  |  Camera: 10.0.0.161

CAMERA_HOSTNAME=yicam-wolff

# ── Stream ────────────────────────────────────────────────────────────────────
RTSP=yes
RTSP_PORT=554
RTSP_USER=
RTSP_PASSWORD=

# ── Local access ──────────────────────────────────────────────────────────────
SSH=yes
TELNET=no
HTTP=yes
HTTP_PORT=80

# ── MQTT (points to gateway PC running Mosquitto) ─────────────────────────────
MQTT=yes
MQTT_HOST=${GatewayIp}
MQTT_PORT=1883
MQTT_USER=
MQTT_PASS=
MQTT_PREFIX=yicam/yhs3017

# ── Disable YI cloud ─────────────────────────────────────────────────────────
CLOUD_UPLOAD=no
P2P=no
PHONE_APP=no
"@

$cfgDest = Join-Path $flashRoot "yi.cfg"
$yiCfg | Set-Content -Path $cfgDest -Encoding ASCII
Write-Host "      Written  : $cfgDest"

# Also write a local copy to flash-config/ for reference
$refCfgDir = Join-Path $PSScriptRoot "..\flash-config"
New-Item -ItemType Directory -Path $refCfgDir -Force | Out-Null
$yiCfg | Set-Content -Path (Join-Path $refCfgDir "yi.cfg") -Encoding ASCII

# ── Step 5: Write to SD card ──────────────────────────────────────────────────
if ($DryRun -or -not $SdDrive) {
    Write-Host ""
    Write-Host "[5/5] DRY RUN — staged files ready at:" -ForegroundColor Magenta
    Write-Host "      $flashRoot"
    Write-Host ""
    Write-Host "  To write to SD card, run:" -ForegroundColor Cyan
    Write-Host "      .\prep-flash-sd.ps1 -SdDrive E" -ForegroundColor White
    Write-Host ""
    Write-Host "  Then on the camera:" -ForegroundColor Cyan
    Write-Host "  1. Insert SD card into camera"
    Write-Host "  2. Power on — LED flashes rapidly during flash (60-90 sec)"
    Write-Host "  3. LED goes solid blue = done"
    Write-Host "  4. RTSP stream: rtsp://10.0.0.161:554/ch0_0.264"
    Write-Host "  5. Web UI:      http://10.0.0.161"
    return
}

$sdPath = "${SdDrive}:\"
if (-not (Test-Path $sdPath)) {
    Write-Error "Drive ${SdDrive}: not found. Insert SD card and check drive letter."
}

# Safety: confirm the drive is small enough to be an SD card (< 65 GB)
$disk = Get-PSDrive -Name $SdDrive
$sizeGB = [math]::Round($disk.Used/1GB + $disk.Free/1GB, 1)
if ($sizeGB -gt 64) {
    Write-Error "Drive ${SdDrive}: is $sizeGB GB — too large for a typical SD card. Aborting."
}

Write-Host "[5/5] Copying firmware to ${SdDrive}: ($sizeGB GB)..." -ForegroundColor Yellow
Write-Host "      WARNING: existing files on ${SdDrive}: will be overwritten." -ForegroundColor Red

$confirm = Read-Host "      Type YES to continue"
if ($confirm -ne "YES") { Write-Host "Cancelled."; exit 0 }

Copy-Item -Path "$flashRoot\*" -Destination $sdPath -Recurse -Force
Write-Host "      Copy complete." -ForegroundColor Green

Write-Host ""
Write-Host "=== SD Card Ready ===" -ForegroundColor Green
Write-Host "  1. Safely eject the SD card."
Write-Host "  2. Insert into YI camera (slot under weather seal)."
Write-Host "  3. Power on camera."
Write-Host "  4. LED flashes rapidly ~60-90 seconds = flashing in progress."
Write-Host "  5. LED solid blue = flash complete — remove SD card."
Write-Host ""
Write-Host "  After boot:" -ForegroundColor Cyan
Write-Host "    RTSP  : rtsp://10.0.0.161:554/ch0_0.264"
Write-Host "    HTTP  : http://10.0.0.161"
Write-Host "    SSH   : ssh root@10.0.0.161  (default pass: root)"
Write-Host "    MQTT  : subscribes to yicam/yhs3017/# on ${GatewayIp}:1883"
Write-Host ""
Write-Host "  Run the gateway then paste the RTSP URL into the dashboard." -ForegroundColor Cyan
